### ISSUE TITLE
when docker_mode is true, got java.net.UnknownHostException: host.docker.internal: System error

### ISSUE THREAD

**Issue by ninggf** [madhead/intellij-http-client-action#25]
/usr/bin/docker run --name ba92399d41c044f39bf5da456f3efa7a8_8bd898 --label 94351b --workdir /github/workspace --rm -e "SERVER_PORT" -e "VER" -e "JAVA_HOME" -e "JAVA_HOME_17_X64" -e "INPUT_FILES" -e "INPUT_ENV_FILE" -e "INPUT_ENV" -e "INPUT_INSECURE" -e "INPUT_DOCKER_MODE" -e "INPUT_SOCKET_TIMEOUT" -e "INPUT_CONNECT_TIMEOUT" -e "INPUT_ENV_VARIABLES" -e "INPUT_PRIVATE_ENV_FILE" -e "INPUT_PRIVATE_ENV_VARIABLES" -e "INPUT_LOG_LEVEL" -e "INPUT_REPORT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/gsvc/gsvc":"/github/workspace" 94351b:a92399d41c044f39bf5da456f3efa7a8
+ java -cp '/intellij-http-client/*' com.intellij.httpClient.cli.HttpClientMain --insecure --env=sit --env-file=apzda-cloud-gsvc-demo/http-client.env.json --docker-mode apzda-cloud-gsvc-demo/bar-test.http apzda-cloud-gsvc-demo/foo-test.http

**Comment by ninggf** [comment]
- name: Execute HTTP requests
        uses: madhead/intellij-http-client-action@latest
        with:
          files: |-
            apzda-cloud-gsvc-demo/bar-test.http
            apzda-cloud-gsvc-demo/foo-test.http
            apzda-cloud-gsvc-demo/demo-test.http
          env_file: apzda-cloud-gsvc-demo/http-client.env.json
          env: dev
          insecure: true
          docker_mode: true

**Comment by madhead** [comment]
Hey, can you please share an request file as well. Or just tell me what are you doing? What do you call?

**Comment by ninggf** [comment]
Hey, I am testing my project(https://github.com/ninggf/gsvc). The request files and github workflow configuration could be found there.

**Comment by madhead** [comment]
Do you really need docker mode here?
